# Generated by Django 2.2.7 on 2019-11-14 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=500)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('D', 'disponible'), ('R', 'reservado')], default='D', max_length=1)),
                ('Tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sesiones.Tipo')),
            ],
        ),
    ]
