# Generated by Django 2.2.7 on 2019-11-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0002_auto_20191114_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
